name: Build and deploy Node.js app to Azure Web App - ai-insurance-agent-mvp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create a lean zip of your app source. Azure (Oryx) will install deps and build.
      - name: Create deployment zip (source only)
        run: |
          rm -f app-source.zip
          zip -r app-source.zip . \
            -x ".git/*" ".github/*" "node_modules/*" ".next/*" "out_azure/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-source
          path: app-source.zip

  deploy:
    runs-on: ubuntu-latest
    needs: package
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-source

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_72B7DD5ACED1414F8BD4C6F9C0EC5E53 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_42FB4EE03C8D42498B926FAB425ABE20 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E479F1FA3D73423398FB8D67F3EFAEE1 }}

      - name: Deploy to Azure Web App (zip)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ai-insurance-agent-mvp
          package: app-source.zip
