name: Build and deploy Node.js app to Azure Web App - ai-insurance-agent-mvp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Optional: basic sanity build in CI (NOT deployed; Azure will build again)
      - name: Install & build (sanity)
        run: |
          npm ci
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .   # deploy the app source (no node_modules)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure login (federated)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_72B7DD5ACED1414F8BD4C6F9C0EC5E53 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_42FB4EE03C8D42498B926FAB425ABE20 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E479F1FA3D73423398FB8D67F3EFAEE1 }}

      # (Optional) force the needed app settings via CLI if you'd rather not toggle in Portal:
      # - name: Ensure App Service build settings
      #   run: |
      #     az webapp config appsettings set -g <RESOURCE_GROUP> -n ai-insurance-agent-mvp \
      #       --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true NPM_CONFIG_PRODUCTION=false WEBSITE_NODE_DEFAULT_VERSION=20-lts NODE_ENV=production

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ai-insurance-agent-mvp
          slot-name: Production
          package: .
