name: Build and deploy Node.js app to Azure Web App - ai-insurance-agent-mvp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  APP_NAME: ai-insurance-agent-mvp          # <-- exact Web App name (matches your screenshot)
  RESOURCE_GROUP: ai-insurance-agent-mvp # <-- fill in your Azure resource group name

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create a lean zip of your app source; Azure (Oryx) will install deps & build
      - name: Create deployment zip (source only)
        run: |
          rm -f app-source.zip
          zip -r app-source.zip . \
            -x ".git/*" ".github/*" "node_modules/*" ".next/*" "out_azure/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-source
          path: app-source.zip

  deploy:
    runs-on: ubuntu-latest
    needs: package
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-source

      - name: Azure login (federated)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_72B7DD5ACED1414F8BD4C6F9C0EC5E53 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_42FB4EE03C8D42498B926FAB425ABE20 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E479F1FA3D73423398FB8D67F3EFAEE1 }}

      - name: Stop app (avoid 409 locks)
        run: az webapp stop -g "$RESOURCE_GROUP" -n "$APP_NAME"

      # Force ZIP DEPLOY via CLI (not OneDeploy)
      - name: Deploy (zipDeploy via CLI)
        run: |
          az webapp deploy \
            --resource-group "$RESOURCE_GROUP" \
            --name "$APP_NAME" \
            --type zip \
            --src-path app-source.zip

      - name: Start app
        run: az webapp start -g "$RESOURCE_GROUP" -n "$APP_NAME"

      - name: Show latest deployment log URL
        run: az webapp log deployment show -g "$RESOURCE_GROUP" -n "$APP_NAME" --query "log_url" -o tsv

